### ISSUE TITLE
ServiceProvider - HasAddress - dcterms not declared in the namespaces

### ISSUE THREAD

**Issue by AlexTombeur** [catalogue-of-services-isa/cos-testing#13]
When filling the HasAddress field of a ServiceProvider class, the dcterms namespace does not appear in the namespace declaration in the .rdf data

Associated test: 31

**Comment by carmenvandeloo** [comment]
Convert.js script was adapted to include the dcterms namespace. 

Bug consisted out of wrongly detecting the dcterms declaration in the rdf:type of Agent due to which the dcterms namespace was not introduced. The dcterms namespace is required because of the dcterms:identifier of the PublicService.

```
<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:ns1="http://data.europa.eu/m8g/">
  <rdf:Description rdf:nodeID="PS_0">
    <rdf:type rdf:resource="http://purl.org/vocab/cpsv#PublicService"/>
    <dcterms:identifier>PS_0</dcterms:identifier>
    <ns1:serviceProvider rdf:nodeID="_4"/>
  </rdf:Description>
  <rdf:Description rdf:nodeID="_4">
    <rdf:type rdf:resource="http://purl.org/dc/terms/Agent"/>
    <ns1:hasAddress>test</ns1:hasAddress>
  </rdf:Description>
</rdf:RDF>
```

**Comment by carmenvandeloo** [comment]
ServiceProvider is no longer a relation between PublicService and Agent in the CPSV-AP 2.1 specification. As such, the Service Provider fields were removed from the description creator. As a result, test 29, 30, 31 were removed. 

The Agent class fields are tested in 13B and 15B (see also issue https://github.com/catalogue-of-services-isa/cos-testing/issues/4)
