### ISSUE TITLE
Deleted content should not appear in the export

### ISSUE THREAD

**Issue by EmidioStani** [catalogue-of-services-isa/cos-testing#17]
I have deleted now (17.22) the "mypo2" Public Organisation, if I click export I still see it and I see all the previous properties (created/modified), it means that the object is never deleted from the triplestore.

  <rdf:Description rdf:about="http://cpsv-ap.semic.eu:8890/cpsv-ap_editor/content/mypo2">
    <rdf:type rdf:resource="http://data.europa.eu/cv/PublicOrganisation" />
    <rdf:type rdf:resource="http://www.w3.org/2000/01/rdf-schema#Class" />
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T15:47:36+02:00</dcterms:created>
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:25:58+02:00</dcterms:created>
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:22:29+02:00</dcterms:created>
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:17:07+02:00</dcterms:created>
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:12:18+02:00</dcterms:created>
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:02:20+02:00</dcterms:created>
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:06:54+02:00</dcterms:created>
    <dcterms:created rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T15:49:47+02:00</dcterms:created>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:12:37+02:00</dcterms:modified>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T15:47:55+02:00</dcterms:modified>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:26:17+02:00</dcterms:modified>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:17:25+02:00</dcterms:modified>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T15:50:06+02:00</dcterms:modified>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:02:39+02:00</dcterms:modified>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:22:48+02:00</dcterms:modified>
    <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:07:13+02:00</dcterms:modified>
    <dcterms:spatial rdf:datatype="http://www.w3.org/2004/02/skos/core#Concept"></dcterms:spatial>
    <skos:preferredLabel rdf:datatype="http://www.w3.org/2000/01/rdf-schema#Literal">mypo2</skos:preferredLabel>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:17:07+02:00</dcterms:date>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:12:18+02:00</dcterms:date>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:22:29+02:00</dcterms:date>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:25:58+02:00</dcterms:date>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T15:47:36+02:00</dcterms:date>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:06:54+02:00</dcterms:date>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T15:49:47+02:00</dcterms:date>
    <dcterms:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2018-07-20T16:02:20+02:00</dcterms:date>
    <dcterms:identifier rdf:datatype="http://www.w3.org/2000/01/rdf-schema#Literal">mypo2</dcterms:identifier>
    <sioc:num_replies rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0</sioc:num_replies>
  </rdf:Description>

**Comment by parreinc** [comment]
Fixed!

Misconfiguration of the RDF indexer, it indexed create/modified dates which are irrelevant.
