### ISSUE TITLE
language selection on top left cannot be selected by user

### ISSUE THREAD

**Issue by EmidioStani** [catalogue-of-services-isa/cos-testing#22]
On top left of the editor there is a sort of language selector, iin reality it shows the current language, but the user cannot use it as selector.

I would suggest:

1) remove the arrow of the dropdown as CSS see: https://stackoverflow.com/questions/16603979/select-removing-dropdown-arrow#answer-32623650
2) grey out by adding the css property opacity: 0.6; otherwise it looks like a text box without arrow

**Comment by parreinc** [comment]
header div was blocking the dropdownbox from being clicked on. Moved it to a lower location.
