### ISSUE TITLE
HasCompetentAuthority - Name

### ISSUE THREAD

**Issue by EmidioStani** [catalogue-of-services-isa/cos-testing#4]
Accordingly to the validator, the name of a Public Organisation (Competent Authority of a Public Service) is a mandatory field.

This field is missing in the Editor.

There are 2 solutions:
1) adding the field in the Editor or
2) removing the rule in the Validator which assumes that a Public Organization is an agent which has the name property mandatory.

As CPOV is not under COS the second solution would be the best.

**Comment by carmenvandeloo** [comment]
PublicOrganisation is defined as: 

```
<http://data.europa.eu/m8g/PublicOrganisation> a rdfs:Class ;
  rdfs:label "PublicOrganisation"@en ;
  vann:usageNote "Mandatory class. The CPSV-AP reuses the Core Public Organisation Vocabulary that defines the concept of a Public Organisation and associated properties and relationships. It is largely based on the W3C Organization Ontology."@en ;
  rdfs:subClassof dct:Agent ;
  rdfs:isDefinedBy cv:cpov .
```

As such, PublicOrganisation inherits all properties and constraints from Agent.

==> Option 1
